# Numpy Basics 

In [1]:
import numpy as np

# Creation of Array

In [2]:
## 1. by simply making one

myarr = np.array([3,6,37,7])
print(myarr)

## 2. by using list

myarr1 = [1,2,3,4,5]
new_arr = np.array(myarr1)
print(new_arr)

## 3. By user input

# l =[]
# for i in range(1,5):
#     int_i = int(input("enter : "))
#     l.append(int_i)

# print(np.array(l))

## 4. By specifying the array

my_arr2 = np.array([3,6,37,7],np.int64)
print(my_arr2)

## 5. BY specifying the dimensions
my_arr3 = np.array([1,2,3,4],ndmin=10)
print(my_arr3.ndim)
print(my_arr3)

## By using numpy Functions

## 1. By using Ones, Zeros 

Zeros = np.zeros((2,5))
print(Zeros)

Ones = np.ones(4)
print(Ones)

## 2. By using arange function

rng = np.arange(15)
print(rng)

## 3. By using linspace 

lspace = np.linspace(1,50,10) ## stop is 
print(lspace)

lspace_2 = np.linspace(1,5,4) 
print()

## 4. By using identity 

ide = np.identity(3)
print(ide)

ide_1 = np.eye(10)
print(ide_1)

## 5. empty

emp = np.empty((4,6))
print(emp)

## 6. emp_like
emp_like = np.empty_like(ide_1)
print(emp_like)


[ 3  6 37  7]
[1 2 3 4 5]
[ 3  6 37  7]
10
[[[[[[[[[[1 2 3 4]]]]]]]]]]
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[1. 1. 1. 1.]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
[ 1.          6.44444444 11.88888889 17.33333333 22.77777778 28.22222222
 33.66666667 39.11111111 44.55555556 50.        ]

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]
[[ 0.00000000e+000  0.00000000e+000  0.00000000e+000 -2.66193215e-310
   0.00000000e+000  0.00000000e+000]
 [ 0.00000000e+000  0.00000000e+000  0.00000000e+000  0.00000000e+000
   0.00000000e+000  0.00000000e+000]
 [ 0.00000000e+000  0.00000000e+000  0.00000000e+000  0.00000000e+000
   0.00000000e+000  0.00000000e+000]
 [ 0.00000000e+000

# Types Of Arrays

In [3]:
# 1-D = [1,2,3,4]
# 2-D = [[1,2,3,4]]
# 3-D = [[[1,2,3,4]]]

## Creating 

# Creating numpy using Random Numbers
#### 1. rand
#### 2. randn
#### 3. randf
#### 4. randint

In [4]:
# 1. rand()
var = np.random.rand(4)
print(var)

# 2. randn()
var1 = np.random.randn(5)
print(var1)

# 3. randint()
var2 = np.random.randint(5,20,5)
print(var2)

# 4. ranf()  # generates numbers betwwen [0.0,1.0)
var3 = np.random.ranf(4)
print(var3)

[0.60722425 0.74862103 0.40888669 0.15595394]
[ 0.86642139  0.41006214  0.20519532  1.61495312 -0.07456893]
[14 12  8 14 13]
[0.59868442 0.62707464 0.1647426  0.89223865]


# Time Excecution

In [5]:
# numpy executes faster:

%timeit [j**4 for j in range(1,9)]

975 ns ± 68.3 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


In [6]:
%timeit np.arange(1,9)**4

2.2 µs ± 70.7 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


# Axis

In [7]:
x = [[1,2,3],[4,5,6],[7,1,0]]
ar = np.array(x)
print(ar)
## rows are axis = 0 
## columns are axis = 1

sum_of_rows = ar.sum(axis=0)
sum_of_columns = ar.sum(axis=1)  

print(f' Columns Wise Sum : {sum_of_rows}')
print(f' Row Wise Sum : {sum_of_columns}')

## always remember when you have find row wise sum ---- take axis = 0
## always remember when you have find row wise sum ---- take axis = 1

[[1 2 3]
 [4 5 6]
 [7 1 0]]
 Columns Wise Sum : [12  8  9]
 Row Wise Sum : [ 6 15  8]


# Others Small Concepts:: 

In [8]:

x = [[1,2,3],[4,5,6],[7,1,0]]
ar = np.array(x)
print(ar)

## For Transpose:
print(f' The Transpose is : {ar.T}')

## For Iterate: 

print()
print("Iteration")
for item in ar.flat:
    print(item)
    
## for finding the size
print()
print("Size of array")
print(ar.size)

## for finding the dimensions
print()
print("The Dimensions of Array : ")
print(ar.ndim)

## for finding the bytes
print()
print("Total Bytes taken by the array : ")
print(ar.nbytes)


[[1 2 3]
 [4 5 6]
 [7 1 0]]
 The Transpose is : [[1 4 7]
 [2 5 1]
 [3 6 0]]

Iteration
1
2
3
4
5
6
7
1
0

Size of array
9

The Dimensions of Array : 
2

Total Bytes taken by the array : 
36


# argsmax , argmin , sort 

In [9]:
## argmax - It is rteurning the index which have the maximum value:-
one = np.array([1,3,4,634,2])
print(one.argmax())

## argmin - It is rteurning the index which have the minimum value:-
print(one.argmin())

## argsort - It returns the sort based on values & return the indices:- 
print(one.argsort())

print()

## Now in 2D 

y = [[1,2,3],[4,5,6],[7,1,0]]

new_y = np.array(y)
print(new_y)
print()

## argsmax
print(new_y.argmax())
print()

## argmin
print(new_y.argmin())
print()

## argmax with axis
print(new_y.argmax(axis=0))
print()

## argmax with axis
print(new_y.argmax(axis=1))
print()

## argsort with axis
print(new_y.argsort(axis=1))
print()

print(new_y.argsort(axis=0))

3
0
[0 4 1 2 3]

[[1 2 3]
 [4 5 6]
 [7 1 0]]

6

8

[2 1 1]

[2 2 0]

[[0 1 2]
 [0 1 2]
 [2 1 0]]

[[0 2 2]
 [1 0 0]
 [2 1 1]]


# Maths Operations: 

#### a+b = np.add(a,b)
#### a-b = np.subtract(a,b)
#### a*b = np.multiply(a,b)
#### a/b = np.divide(a,b)
#### a%b = np.mod(a,b)
#### a**b = np.power(a,b)
#### 1/a = np.reciporal
#### np.min(x)
#### np.max(x)
#### np.argmax(x)
#### np.sqrt(x)
#### np.sin(x)
#### np.cos(x)
#### np.cumsum(x)

In [10]:
## add 
var = np.array([[1,2,3],[4,5,6],[7,1,10]])
var_ = np.array([[1,2,1],[4,0,6],[8,1,0]])

# if i wnat to add just one element
var_5= var+100
print(var_5)

var_1 = var+var_
print(var_1)
print()

## for multiply
var_2 = var*var_
print(var_2)
print()

print("The Sqrt : ")
print(np.sqrt(var))
print()
## for sum of all elements: - 
print(var.sum())

## for max of all elements:-  
print(var.max())

## for min of all elements:-  
print(var.min())

## by using numpy functions
print(np.add(var,var_))
print()

print(np.subtract(var,var_))
print()

print(np.multiply(var,var_))
print()

print(np.divide(var,var_))
print()

print(np.mod(var,var_))
print()

print(np.power(var,var_))
print()

print(np.reciprocal(var,var_))
print()

print(np.max(var))
print()

print(np.min(var))
print()

print(np.argmin(var))
print()

print(np.argmax(var))
print()

print(np.sqrt(var))
print()

print(np.sin(var))
print()

print(np.cos(var))
print()

print(np.cumsum(var))
print()


[[101 102 103]
 [104 105 106]
 [107 101 110]]
[[ 2  4  4]
 [ 8  5 12]
 [15  2 10]]

[[ 1  4  3]
 [16  0 36]
 [56  1  0]]

The Sqrt : 
[[1.         1.41421356 1.73205081]
 [2.         2.23606798 2.44948974]
 [2.64575131 1.         3.16227766]]

39
10
1
[[ 2  4  4]
 [ 8  5 12]
 [15  2 10]]

[[ 0  0  2]
 [ 0  5  0]
 [-1  0 10]]

[[ 1  4  3]
 [16  0 36]
 [56  1  0]]

[[1.    1.    3.   ]
 [1.      inf 1.   ]
 [0.875 1.      inf]]

[[0 0 0]
 [0 0 0]
 [7 0 0]]

[[      1       4       3]
 [    256       1   46656]
 [5764801       1       1]]

[[1 0 0]
 [0 0 0]
 [0 1 0]]

10

1

0

8

[[1.         1.41421356 1.73205081]
 [2.         2.23606798 2.44948974]
 [2.64575131 1.         3.16227766]]

[[ 0.84147098  0.90929743  0.14112001]
 [-0.7568025  -0.95892427 -0.2794155 ]
 [ 0.6569866   0.84147098 -0.54402111]]

[[ 0.54030231 -0.41614684 -0.9899925 ]
 [-0.65364362  0.28366219  0.96017029]
 [ 0.75390225  0.54030231 -0.83907153]]

[ 1  3  6 10 15 21 28 29 39]



C:\Users\amarj\AppData\Local\Temp\ipykernel_30420\1889570109.py:40: RuntimeWarning: divide by zero encountered in divide
  print(np.divide(var,var_))
C:\Users\amarj\AppData\Local\Temp\ipykernel_30420\1889570109.py:43: RuntimeWarning: divide by zero encountered in remainder
  print(np.mod(var,var_))


# Other Concepts: - 

In [11]:
## count_non_Zero
arr = [[1,2,3],[4,5,6],[7,1,0]]
arr = np.array(arr)
print(np.count_nonzero(arr))
print(np.nonzero(arr))


## if i upaate then
arr[1,2]=0
print(np.nonzero(arr))



8
(array([0, 0, 0, 1, 1, 1, 2, 2], dtype=int64), array([0, 1, 2, 0, 1, 2, 0, 1], dtype=int64))
(array([0, 0, 0, 1, 1, 2, 2], dtype=int64), array([0, 1, 2, 0, 1, 0, 1], dtype=int64))


# Reshape, Shape, Ravel

In [12]:
arr =  np.arange(99)
print(arr)
print()
## It convert array in your desire dimensions

my_arr = arr.reshape(3,33)
print(my_arr)
print()
## ravel: - it convert the N Dim Array in 1D Array
print(my_arr.ravel())
print()
print(my_arr.reshape(-1))

## Now in 2d array
arr = [[1,2,3],[4,5,6],[7,1,0]]
arr_new = np.array(arr)

print(arr_new.shape)
print(arr_new.reshape(9,1))
## print(arr_new.ravel())
print(arr_new.reshape(-1))

new_array = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
x1 = new_array.reshape(2,3,2)
print(x1)
print(x1.ndim)


[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98]

[[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
  24 25 26 27 28 29 30 31 32]
 [33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55 56
  57 58 59 60 61 62 63 64 65]
 [66 67 68 69 70 71 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89
  90 91 92 93 94 95 96 97 98]]

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98]

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 2

# Other Concepts : 

In [13]:
## numpy takes less space as compared to array:- 
import sys

py_ar = [0,4,55,2]

np_ar = np.array(py_ar)
## size of each element of a list
print(sys.getsizeof(py_ar))
## memmory take by list
print(sys.getsizeof(py_ar)*len(py_ar))
## memmory take by array
print(np_ar.itemsize*np_ar.size)


88
352
16


# Data Type Conversion

In [14]:
# var = np.array([1,2,3,4,12,13,14,15])  ---- int 32
# var = np.array(["A","S","D","F"])     ----- string <U1
# var = np.array([1.0,1.2,1.3])  ---- float 64
# var = np.array(["A","S","D","F",,2,3,4,12])  ---- int 32
# i = integer
# b = boolean
# u = unsigned
# f = float
# c = complex float
# t = timedelta
# m = datetime
# O = object
# S = String
# U = Unicode String
# V = The fixed chunk of memory for type(void)

# 1. 
x = np.array([1,2,34],dtype=np.int8)
print("Data Type : ",x.dtype)
print(x)

# 2. 
x1 = np.array([1,2,34],dtype='f')
print("Data Type : ",x1.dtype)
print(x1)

# 3.
x2 = np.array([1,2,3,4])
new = np.float32(x2)
new_one = np.int_(new)


print("Data Type : ",x2.dtype)
print("Data Type : ",new.dtype)
print("Data Type : ",new_one.dtype)

# 3. 
x3 = np.array([1,2,3,4])
new_3 = x3.astype(float)
print(x3)
print(new_3)




Data Type :  int8
[ 1  2 34]
Data Type :  float32
[ 1.  2. 34.]
Data Type :  int32
Data Type :  float32
Data Type :  int32
[1 2 3 4]
[1. 2. 3. 4.]


# Indexing and Slicing

In [15]:
# in 1D Array
var = np.array([9,8,7,6])
print(var[0])

# in 2D Array
var1 = np.array([[9,8,7],[4,5,6]])
print(var1[0,2])


# slicing in 1D 
var = np.array([9,8,7,6,5,4,3])
print("2 to 5 ", var[1:5])
print("2 to end ", var[1:])
print("Start to 5 ", var[:5])
print("stop ", var[1:5:2])

a = [[1,2,3,4],[1,3,4,1],[1,0,10,1]]
a= np.array(a)
print(a[2,1:])
print(a[0:2,1:4])
print(a[:2,2])



9
7
2 to 5  [8 7 6 5]
2 to end  [8 7 6 5 4 3]
Start to 5  [9 8 7 6 5]
stop  [8 6]
[ 0 10  1]
[[2 3 4]
 [3 4 1]]
[3 4]


# iteration

In [16]:
a_ = [[1,2,3,4],[1,3,4,1],[1,0,10,1]]
a_new = np.array(a_)
# in 2D Array ---
for k in a_new :
    for l in k:
        print(k)

# in 3D Array ---
# for l in var3:
#     for j in i:
#         for k in j:
#             print(k)


# If you do not want to iterate through a nested loop:-

var_3 = np.array([[[9,8,7,6],[1,2,3,4]]])

for i in np.nditer(var_3):
    print(i)

# if i want to iterate along with values:-

for i in np.ndenumerate(var_3):
    print(i)
    




[1 2 3 4]
[1 2 3 4]
[1 2 3 4]
[1 2 3 4]
[1 3 4 1]
[1 3 4 1]
[1 3 4 1]
[1 3 4 1]
[ 1  0 10  1]
[ 1  0 10  1]
[ 1  0 10  1]
[ 1  0 10  1]
9
8
7
6
1
2
3
4
((0, 0, 0), 9)
((0, 0, 1), 8)
((0, 0, 2), 7)
((0, 0, 3), 6)
((0, 1, 0), 1)
((0, 1, 1), 2)
((0, 1, 2), 3)
((0, 1, 3), 4)


# Copy and View

In [17]:
# copy - The owns the data 
#        The copy of an array is a new array
#        The Changes made in the copy data does not reflect in the original array.

# View - The View does not own the data a view of the original array
#        A view of the array
#        Any Changes made to the view will affect the original array & any chnages made to the original array will affect the view.

In [18]:
x = np.array([9,8,7,6])
copy = x.copy()
print(copy)
view = x.view()
print(view)


[9 8 7 6]
[9 8 7 6]


# Join and Split

In [19]:
var = np.array([1,2,3,4])
var_1 = np.array([9,8,7,6])
ar = np.concatenate((var,var_1))
print('join')
print(ar)

var = np.array([[1,2],[3,4]])
var_1 = np.array([[9,8],[7,6]])
ar = np.concatenate((var,var_1))
ar_1 = np.concatenate((var,var_1),axis=1)
ar_2 = np.concatenate((var,var_1),axis=0)
print('join')
print(ar)
print(ar_1)
print(ar_2)
print()
print()
print()
## Stack 
## H_Stack - rows
## V_Stack - colums 
## D_Stack - height
stack_1 = np.array([1,2,3,4])
stack_2 = np.array([9,8,7,6])
print('hstack')
new_stack = np.stack([stack_1,stack_2])
print(new_stack)

print('vstack')
new_stack = np.vstack([stack_1,stack_2])
print(new_stack)

print('dstack')
new_stack = np.dstack([stack_1,stack_2])
print(new_stack)



# Spilt 

var = [1,2,3,4,5,6]
print(var)
print('split')
ar = np.array_split(var,3)
print(ar)

var_10 = np.array([[1,2],[3,4],[5,4]])
print(var_10)
var_10_split = np.array_split(var_10,3)
print(var_10_split)

# by axis
var_10_split_ = np.array_split(var_10,3,axis=1)
print(var_10_split_)

join
[1 2 3 4 9 8 7 6]
join
[[1 2]
 [3 4]
 [9 8]
 [7 6]]
[[1 2 9 8]
 [3 4 7 6]]
[[1 2]
 [3 4]
 [9 8]
 [7 6]]



hstack
[[1 2 3 4]
 [9 8 7 6]]
vstack
[[1 2 3 4]
 [9 8 7 6]]
dstack
[[[1 9]
  [2 8]
  [3 7]
  [4 6]]]
[1, 2, 3, 4, 5, 6]
split
[array([1, 2]), array([3, 4]), array([5, 6])]
[[1 2]
 [3 4]
 [5 4]]
[array([[1, 2]]), array([[3, 4]]), array([[5, 4]])]
[array([[1],
       [3],
       [5]]), array([[2],
       [4],
       [4]]), array([], shape=(3, 0), dtype=int32)]


# Search, Search Sorted, Sorted array, filter array

In [20]:
var = np.array([1,2,3,4,5,6,7])
# Linear Search ---- it will return the indices where element is present..
x=np.where(var==1)
print(x)

# Search Sorted Array
var1 = np.array([1,2,3,4,5,6,7,8])
x1 = np.searchsorted(var1,5) # element needs to be sorted
x2 = np.searchsorted(var1,[5,6,7],side='right')
print(x1)
print(x2)

# Sort Array
var_1 = np.array([4,2,4,2,5,2,5,6,7])
print(np.sort(var_1))

var_2 = np.array([[4,2,3],[1,12,5],[22,52,6]])
print(np.sort(var_2))

# Filter Array

var_3 = np.array(['a','s','d','f'])
F = [True,False,False,True]
new_a = var_3[F] ## it will return values which have true in it.
print(new_a)

(array([0], dtype=int64),)
4
[5 6 7]
[2 2 2 4 4 5 5 6 7]
[[ 2  3  4]
 [ 1  5 12]
 [ 6 22 52]]
['a' 'f']


# Shuffle, Unique, Resize, Flatten

In [21]:
# Shyffle
var = np.array([1,2,3,4,5])
np.random.shuffle(var)
print(var)

# Unique - removing duplicates 
var = np.array([1,2,3,1,1,1,2,2,3,4,5,6,7])
print(np.unique(var))

var_ = np.unique(var1,return_index=True,return_counts= True)
print(var_)

# resize 
var_2 = np.array([1,2,3,4,5,6])
y = np.resize(var_2,(2,3))
print(y)

print("Flatten : ",y.flatten(order='f'))
print("Ravel : ",np.ravel(y,order='f'))



[1 4 5 3 2]
[1 2 3 4 5 6 7]
(array([1, 2, 3, 4, 5, 6, 7, 8]), array([0, 1, 2, 3, 4, 5, 6, 7], dtype=int64), array([1, 1, 1, 1, 1, 1, 1, 1], dtype=int64))
[[1 2 3]
 [4 5 6]]
Flatten :  [1 4 2 5 3 6]
Ravel :  [1 4 2 5 3 6]


# insert and delete

In [22]:
var = np.array([1,2,3,4])
print(var)
v = np.insert(var,(1,2),40) ## same value at multiple index
print(v)

var_1 = np.array([[1,2,3],[1,2,3]])
v_1 = np.insert(var_1,1,[22,23,24],axis=0) ## it will add the values at a partcular row as per the position given
print(v_1)

# works with append -- 
x = np.append(var,6.5)
print(x)

## delete --
var_1 = np.array([1,2,3,4])
d = np.delete(var_1,2) ## delete the value at givem index
print(d)

[1 2 3 4]
[ 1 40  2 40  3  4]
[[ 1  2  3]
 [22 23 24]
 [ 1  2  3]]
[1.  2.  3.  4.  6.5]
[1 2 4]


# MATRIX FUNCTIONS

In [51]:
mat = np.matrix([[1,2,3],[1,2,3]])
mat_2 = np.matrix([[1,2,3],[1,2,3]])
print(mat)
print(mat_2)
print()
# # multiply
# print(mat*mat_2)
# print(mat.dot(mat_2))

# 
var = np.matrix([[1,2,2],[4,5,6]])
print(var)
print()
Arr = var.transpose()
print(Arr)


[[1 2 3]
 [1 2 3]]
[[1 2 3]
 [1 2 3]]

[[1 2 2]
 [4 5 6]]

[[1 4]
 [2 5]
 [2 6]]


In [53]:
## Swapaxes:- 

np.swapaxes(var,0,1)


matrix([[1, 4],
        [2, 5],
        [2, 6]])

In [54]:
## to find the inverse 
var = np.matrix([[1,2,3],[4,5,6],[7,8,9]])
print(np.linalg.inv(var))

[[ 3.15251974e+15 -6.30503948e+15  3.15251974e+15]
 [-6.30503948e+15  1.26100790e+16 -6.30503948e+15]
 [ 3.15251974e+15 -6.30503948e+15  3.15251974e+15]]


In [55]:
## to find the power
var = np.matrix([[1,2,3],[4,5,6],[7,8,9]])
print(np.linalg.matrix_power(var,0))

## n= 0 -- identity 
## n>0 --  power() = A*A
## n<0 -- power() = inverse * power


[[1 0 0]
 [0 1 0]
 [0 0 1]]


In [59]:
## determinat

np.linalg.det(var)

-9.51619735392994e-16